//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentList
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStudent
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string StudentID { get; set; }
        public System.DateTime Birthday { get; set; }
        public string FatherName { get; set; }
        public Nullable<int> NasionalCode { get; set; }
        public string CityCertificate { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string FK_FieldOfStudy { get; set; }
    
        public virtual TblFindOfStudy TblFindOfStudy { get; set; }
    }
}
